name: 'Docker Tag for AWS ECR'
description: 'Tags an AWS ECR Docker image without pulling it'
inputs:
  region:
    description: 'The AWS region'
    required: true
  registry-id:
    description: 'The AWS account ID associated with the registry that contains the repository and image'
    required: false
  repository-name:
    description: 'The name of the repository in which to get and put the image'
    required: true
  source-image-tag:
    description: 'The existing tag to find the image'
    required: true
  target-image-tag:
    description: 'The new tag to add to the image'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
